### ISSUE TITLE
Frontend improvements and suggestions

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#1]
Hey, hi! Here I will be making some observations and suggestions from my perspective. I will be reviewing your code

**Comment by ASASauqui** [comment]
The header of the page is not visible, it is hidden by the navbar, the same thing happens in the register page, it could be a good option to add a general top padding in the root.html.heex that covers <%= @inner_content %>

https://github.com/Josue0H/betsnap/blob/897c6c584607dc6daefdc745fe6a20074c430841/lib/betsnap_web/live/user_login_live.ex#L7-L16

**Comment by ASASauqui** [comment]
It doesn't let me scroll through the countries (sidebar), I think that instead of an "h-auto", an "h-full" would be better, because with h-full you would take the entire height of the parent and then the logic of the overflow would make sense.

https://github.com/Josue0H/betsnap/blob/897c6c584607dc6daefdc745fe6a20074c430841/lib/betsnap_web/components/custom_components.ex#L78

**Comment by ASASauqui** [comment]
<img width="1084" alt="Screenshot 2024-03-05 at 3 07 13 p m" src="https://github.com/Josue0H/betsnap/assets/98852683/6cf03fe1-36b8-48c9-be45-d4e0955c2142">

It would be a very good option to have the images change automatically.

**Comment by ASASauqui** [comment]
The responsiveness can improve, but in general it behaves very well, I would put a min-w-[350px], personally I always like to limit the width of the applications like Apple, Facebook, Disney, etc. do.

And personally, I have never seen any sense that it can be minimized to infinity hahaha, it is very problematic :c

**Comment by ASASauqui** [comment]
https://github.com/Josue0H/betsnap/blob/897c6c584607dc6daefdc745fe6a20074c430841/lib/betsnap_web/live/home_live.html.heex#L1

As a suggestion, it is better to implement flash in app.html.heex or in a global file, since they will always be used.

**Comment by ASASauqui** [comment]
Try making a commit by trying this new command:

`mix format`

This will format your entire project, it is very useful so that the entire project has the same formatting style :D

**Comment by Josue0H** [comment]
Solved in: 13e95013f38943a27100981d84997a84dddae9b4

**Comment by ASASauqui** [comment]
I will close this issue because I made a mistake and put everything here instead of breaking it down by individual issues
