### ISSUE TITLE
Improvement: Show images automatically

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#10]
<img width="1084" alt="Screenshot 2024-03-05 at 3 07 13 p m" src="https://github.com/Josue0H/betsnap/assets/98852683/6cf03fe1-36b8-48c9-be45-d4e0955c2142">

It would be a very good option to have the images change automatically.

**Comment by Josue0H** [comment]
Solved in: 13e95013f38943a27100981d84997a84dddae9b4

**Comment by ASASauqui** [comment]
I can see it working now, great!
