### ISSUE TITLE
Improvement: Improved responsiveness

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#11]
The responsiveness can improve, but in general it behaves very well, I would put a min-w-[350px], personally I always like to limit the width of the applications like Apple, Facebook, Disney, etc. do.

And personally, I have never seen any sense that it can be minimized to infinity hahaha, it is very problematic :c

**Comment by Josue0H** [comment]
Solved in: 13e95013f38943a27100981d84997a84dddae9b4
