### ISSUE TITLE
Improvement: Flash tag could be global

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#12]
https://github.com/Josue0H/betsnap/blob/897c6c584607dc6daefdc745fe6a20074c430841/lib/betsnap_web/live/home_live.html.heex#L1

As a suggestion, it is better to implement flash in app.html.heex or in a global file, since they will always be used.

**Comment by Josue0H** [comment]
Solved in: 13e95013f38943a27100981d84997a84dddae9b4

**Comment by ASASauqui** [comment]
Now you avoid having to put that tag in each html file, nice!
