### ISSUE TITLE
Suggestion: Adding format with this command! :D

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#13]
Try making a commit by trying this new command:

`mix format`

This will format your entire project, it is very useful so that the entire project has the same formatting style :D

**Comment by Josue0H** [comment]
Solved in: 13e95013f38943a27100981d84997a84dddae9b4

**Comment by ASASauqui** [comment]
Try, before pushing each commit, to run the `mix format` command, to format your project, but very good

**Comment by ASASauqui** [comment]
Try, before pushing each commit, to run the mix format command, to format your project, but very good

**Comment by ASASauqui** [comment]
Try, before pushing each commit, to run the `mix format` command, to format your project, but very good
