### ISSUE TITLE
Improvement: Code reduction opportunity at BetsnapWeb.Utils.BetChecker

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#14]
https://github.com/Josue0H/betsnap/blob/897c6c584607dc6daefdc745fe6a20074c430841/lib/betsnap_web/utils/bet_checker.ex#L26-L38

I see that this is repeated too much, you could still make a function that handles this logic and reduce the code.

**Comment by Josue0H** [comment]
Solved in: 13e95013f38943a27100981d84997a84dddae9b4
