### ISSUE TITLE
Suggestion: Separation of responsibilities Entity-CRUD

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#16]
https://github.com/Josue0H/betsnap/blob/897c6c584607dc6daefdc745fe6a20074c430841/lib/betsnap/bet.ex#L32-L121

Personally, I prefer to leave a single file for managing the entity with the DB, and another independent file only for the CRUD and any other information management.

Could be like this:

-bet.ex
--Schema
--Validations

-bets.ex
--CRUD
--Other information exchanges

If the above was not understood, see the following files as an example: account.ex and accounts.ex

**Comment by FeeJai** [comment]
I recommend to follow standard practices: https://hexdocs.pm/phoenix/contexts.html

**Comment by Josue0H** [comment]
Solved in: 13e95013f38943a27100981d84997a84dddae9b4

**Comment by ASASauqui** [comment]
I see the separation of responsibilities well, although I would put the bets.ex file in the betsnap root, like the accounts.ex file is for example. But it doesn't matter, it's good that way, well done
