### ISSUE TITLE
Suggestion: Using environment variables

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#17]
https://github.com/Josue0H/betsnap/blob/897c6c584607dc6daefdc745fe6a20074c430841/lib/betsnap_web/api/sports_api.ex#L1-L4

It could be a good exercise to put this api key in an .env file so that it remains secret. You can use the dotenv library and make the necessary configuration for it to work.

https://hex.pm/packages/dotenv

**Comment by FeeJai** [comment]
Compare: https://12factor.net/

**Comment by Josue0H** [comment]
Solved in: 13e95013f38943a27100981d84997a84dddae9b4
