### ISSUE TITLE
Improvements and suggestions for the use of elixir and phoenix

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#2]
Currently many of the processes are not asynchronous and the application gets stuck when the data is requested. A good option to make requests asynchronous and implement a loader while the data is requested can be the use of send() and handle_info/2.

I share with you an example that is in this repository:

https://github.com/allanegidio/food_order/blob/00f88a163e15516c3978d4b3db483b35f5b1d14c/lib/food_order_web/live/admin/product_live/index/index.ex#L72-L82

Docs:
https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:handle_info/2

**Comment by ASASauqui** [comment]
The application crashed when I tried to see a bet without being logged in, it redirected me to login and I returned to see the page again, and then this crash appears.

<img width="1350" alt="Screenshot 2024-03-05 at 2 12 29 p m" src="https://github.com/Josue0H/betsnap/assets/98852683/d9f6c767-aef7-4a44-b5dd-ffec982e96a6">

It's probably a case in your handle_params where you need to use :show_modal but in that specific case handle_params is not declared. Try to declare all your variables in the mount(), and if they are not going to be used in a specific case, put a value that you can manage in case there is no use

**Comment by ASASauqui** [comment]
The page loads correctly, but I don't know why it crashes after a few seconds.

<img width="1352" alt="Screenshot 2024-03-05 at 2 19 55 p m" src="https://github.com/Josue0H/betsnap/assets/98852683/ce144b6a-e862-4dd4-bfeb-18f36334fa45">

**Comment by ASASauqui** [comment]
https://github.com/Josue0H/betsnap/blob/897c6c584607dc6daefdc745fe6a20074c430841/lib/betsnap_web/live/match_live.ex#L28-L38

You can do this logic directly in the {:noreply, socket}.

Like:

`
 {:noreply, 
assign( 
   socket, 
   match: match, 
   active_tab: active_tab, 
   odd: odd, 
   value: value, 
   show_modal: true, 
   bet: bet, 
   stake: "") } 
`

Well, personally I like working that way, I feel like it's less repetitive hahaha

**Comment by ASASauqui** [comment]
https://github.com/Josue0H/betsnap/blob/897c6c584607dc6daefdc745fe6a20074c430841/lib/betsnap_web/components/match_tabs.ex#L22-L30

This works, but in case there is an error there is no way to manage it and the application will crash. And instead of doing very complicated nesting you can use the "with" flow structure. I attach this page that explains its use very well and gives you examples:

https://dev.to/martinthenth/using-elixirs-with-statement-5e36

**Comment by ASASauqui** [comment]
Everything was moved to separate issues

**Comment by Josue0H** [comment]
Solved in: 13e95013f38943a27100981d84997a84dddae9b4

**Comment by ASASauqui** [comment]
I will close this issue because I made a mistake and put everything here instead of breaking it down by individual issues
