### ISSUE TITLE
Suggestion: Credo analyzer implementation

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#20]
Credo is an analyzer, once you have installed it you can run the following command and see the opportunities for improvement and errors that your project has:

`mix credo`

**Using credo in your project:**
<img width="865" alt="Screenshot 2024-03-05 at 4 39 11 p m" src="https://github.com/Josue0H/betsnap/assets/98852683/292c295b-90c3-492c-800c-1788f5af5299">

**Docs:**
https://hexdocs.pm/credo/installation.html
https://hexdocs.pm/credo/basic_usage.html

**Comment by sahid99** [comment]
Thank you Alan for spotting this but right now I don't think we should enforce all of the credo rules. Using mix format should be enough for this small project.

**Comment by FeeJai** [comment]
Now that the app is online and you have improved it a lot, I think we should reopen this ticket
