### ISSUE TITLE
Fix: Crash due to lack of declaration of an assignment

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#4]
The application crashed when I tried to see a bet without being logged in, it redirected me to login and I returned to see the page again, and then this crash appears.

<img width="1350" alt="Screenshot 2024-03-05 at 2 12 29 p m" src="https://github.com/Josue0H/betsnap/assets/98852683/d9f6c767-aef7-4a44-b5dd-ffec982e96a6">

It's probably a case in your handle_params where you need to use :show_modal but in that specific case handle_params is not declared. Try to declare all your variables in the mount(), and if they are not going to be used in a specific case, put a value that you can manage in case there is no use

**Comment by Josue0H** [comment]
Solved in: 13e95013f38943a27100981d84997a84dddae9b4
