### ISSUE TITLE
Fix: Crashing after seconds on country page

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#5]
The page loads correctly, but I don't know why it crashes after a few seconds.

<img width="1352" alt="Screenshot 2024-03-05 at 2 19 55 p m" src="https://github.com/Josue0H/betsnap/assets/98852683/ce144b6a-e862-4dd4-bfeb-18f36334fa45">

**Comment by Josue0H** [comment]
Solved in: 13e95013f38943a27100981d84997a84dddae9b4

**Comment by ASASauqui** [comment]
Now I get this error when I go to a country page, and select a match:

<img width="1364" alt="Screenshot 2024-03-12 at 11 39 12 a m" src="https://github.com/Josue0H/betsnap/assets/98852683/05fdc3ca-55bc-4a37-9f42-2da2ea3f8c18">


<img width="1070" alt="Screenshot 2024-03-12 at 11 40 31 a m" src="https://github.com/Josue0H/betsnap/assets/98852683/345ed898-b777-407d-a6ad-f03a0fddd22f">

**Comment by Josue0H** [comment]
Solved in: 9fced204892da60ba1b5f75b9bb1c19cd8c7703b
