### ISSUE TITLE
Suggestion: Code simplification in {:noreply, socket}

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#6]
https://github.com/Josue0H/betsnap/blob/897c6c584607dc6daefdc745fe6a20074c430841/lib/betsnap_web/live/match_live.ex#L28-L38

You can do this logic directly in the {:noreply, socket}.

Like:

`
 {:noreply, 
assign( 
   socket, 
   match: match, 
   active_tab: active_tab, 
   odd: odd, 
   value: value, 
   show_modal: true, 
   bet: bet, 
   stake: "") } 
`

Well, personally I like working that way, I feel like it's less repetitive hahaha

**Comment by Josue0H** [comment]
Solved in: 13e95013f38943a27100981d84997a84dddae9b4

**Comment by ASASauqui** [comment]
This was a suggestion, but I think it's great that you implemented it, it reduces a lot of unnecessary code and it looks better!
