### ISSUE TITLE
Improvement: Using the "with" flow structure for request handling

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#7]
https://github.com/Josue0H/betsnap/blob/897c6c584607dc6daefdc745fe6a20074c430841/lib/betsnap_web/components/match_tabs.ex#L22-L30

This works, but in case there is an error there is no way to manage it and the application will crash. And instead of doing very complicated nesting you can use the "with" flow structure. I attach this page that explains its use very well and gives you examples:

https://dev.to/martinthenth/using-elixirs-with-statement-5e36

**Comment by Josue0H** [comment]
Solved in: 13e95013f38943a27100981d84997a84dddae9b4

**Comment by ASASauqui** [comment]
I see that you implemented it, perfect, now it is easier to handle errors instead of the application crashing
