### ISSUE TITLE
Improvement: Navbar hides headers

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#8]
The header of the page is not visible, it is hidden by the navbar, the same thing happens in the register page, it could be a good option to add a general top padding in the root.html.heex that covers <%= @inner_content %>

https://github.com/Josue0H/betsnap/blob/897c6c584607dc6daefdc745fe6a20074c430841/lib/betsnap_web/live/user_login_live.ex#L7-L16

**Comment by Josue0H** [comment]
Solved in: 13e95013f38943a27100981d84997a84dddae9b4

**Comment by ASASauqui** [comment]
Now the navbar does not cover information, perfect!
