### ISSUE TITLE
Fix: Scroll does not work in sidebar to list countries

### ISSUE THREAD

**Issue by ASASauqui** [Josue0H/betsnap#9]
<img width="664" alt="Screenshot 2024-03-05 at 3 46 12 p m" src="https://github.com/Josue0H/betsnap/assets/98852683/87ddb35b-01b5-403a-a939-5c18c0cede0e">

It doesn't let me scroll through the countries (sidebar), I think that instead of an "h-auto", an "h-full" would be better, because with h-full you would take the entire height of the parent and then the logic of the overflow would make sense.

https://github.com/Josue0H/betsnap/blob/897c6c584607dc6daefdc745fe6a20074c430841/lib/betsnap_web/components/custom_components.ex#L78

**Comment by Josue0H** [comment]
Solved in: 13e95013f38943a27100981d84997a84dddae9b4

**Comment by ASASauqui** [comment]
Now that works correctly, well done

**Comment by ASASauqui** [comment]
Now that works correctly, well done
